### ISSUE TITLE
Can't use require inside of setup.

### ISSUE THREAD

**Issue by cobbdb** [bestiejs/benchmark.js#105]
After reading #94 I am using the global.require workaround successfully, but hoping this can be fixed in the library instead of having to use a workaround.

```javascript
var Benchmark = require('benchmark'),
    suite = Benchmark.Suite();

function dosetup() {
    var myModule = require('../src/my-module.js'); // <-- Cannot find require.
}

suite.
    add('mytest', {
        setup: dosetup,
        fn: function () {}
    }).
    run();
```

**Comment by jdalton** [comment]
This is fixed in the master branch.

**Comment by gajus** [comment]
This getting this:

```js
var Benchmark,
    runBenchmark;

Benchmark = require('benchmark');

runBenchmark = (name, fn, options) => {
    options = options || {};

    new Benchmark.Suite()
        .add(name, {
            fn,
            setup: options.setup
        })
        .on('start', (event) => {
            console.log('starting', event.target.name);
        })
        .on('cycle', (event) => {
            console.log('target', String(event.target));
        })
        .on('error', (event) => {
            console.log('error', String(event.target.error));
        })
        .run();
};

runBenchmark('Third test', () => {
    /o/.test(target);
}, {
    setup () {
        var combineReducers,
            createCombineReducers;

        createCombineReducers = require('./../dist/createCombineReducers');
        combineReducers = createCombineReducers();
    }
});

```

```
starting Third test
error ReferenceError: require is not defined
target Third test:
```

**Comment by gajus** [comment]
Looks like adding `global.require = require;` makes it work. If this is a requirement, should it be documented?

**Comment by jdalton** [comment]
@gajus What version are you using?

**Comment by gajus** [comment]
2.1.0

**Comment by gajus** [comment]
@jdalton You can test it here. https://github.com/gajus/redux-immutable/tree/v3.0.0

```sh
git clone https://github.com/gajus/redux-immutable.git
cd ./redux-immutable
npm install
npm run build
# Comment out https://github.com/gajus/redux-immutable/blob/v3.0.0/benchmarks/index.js#L6
npm run benchmark
```

**Comment by akloeber** [comment]
@jdalton: This issue should be reopened as using `require` inside the `setup` function still does not work:
```js
var Benchmark = require('benchmark');

new Benchmark.Suite()
.add('foo', {
  fn: function() {
    assert.equal(3, DATA.length);
  },
  setup: function () {
    try {
      var assert = require('assert');
      var DATA = [1, 2, 3];
    } catch (err) {
      console.log('SETUP ERROR', err);
    }
  }
})
.on('error', event => console.error('TEST ERROR:', event.target.error.stack))
.on('cycle', event => console.log(String(event.target)))
.run({'async': true});
```
```bash
$ node test/perf.test.js 
SETUP ERROR [ReferenceError: require is not defined]
SETUP ERROR [ReferenceError: require is not defined]
TEST ERROR: TypeError: Cannot read property 'equal' of undefined
    at Benchmark.eval [as compiled] (eval at createCompiled (/Users/aske/Repos/stream-eval/node_modules/benchmark/benchmark.js:1725:16), <anonymous>:10:66)
    at clock (/Users/aske/Repos/stream-eval/node_modules/benchmark/benchmark.js:1621:50)
    at clock (/Users/aske/Repos/stream-eval/node_modules/benchmark/benchmark.js:1818:20)
    at cycle (/Users/aske/Repos/stream-eval/node_modules/benchmark/benchmark.js:2007:49)
    at Benchmark.run (/Users/aske/Repos/stream-eval/node_modules/benchmark/benchmark.js:2114:13)
    at execute (/Users/aske/Repos/stream-eval/node_modules/benchmark/benchmark.js:860:74)
    at null.<anonymous> (/Users/aske/Repos/stream-eval/node_modules/lodash/lodash.js:2761:43)
    at Timer.listOnTimeout (timers.js:92:15)
sync: 
```
It does work in the test function itself where also other variables from the module scope can be accessed as expected.

As a workaround `require` and everything else from the module scope that is used has to be put on the global scope like this:
```js
global.require = require;
```
On the other hand your comment https://github.com/bestiejs/benchmark.js/issues/94#issuecomment-110435678 suggests that using `require` should work as expected without any precautions.

__Environment:__
benchmark@2.1.3
node v4.4.1
Mac OS X 10.11.6
