### ISSUE TITLE
Uncaught TypeError: benchmark.Suite is not a constructor

### ISSUE THREAD

**Issue by feross** [bestiejs/benchmark.js#128]
The following code fails using the npm package with Browserify:

```js
var benchmark = require('benchmark')
var suite = benchmark.Suite()
```

With the following error:

```
Uncaught TypeError: benchmark.Suite is not a constructor
```

You can quickly see it happening if you use [RequireBin](http://requirebin.com/) and paste the above code.

**Comment by feross** [comment]
Happens with v2.0.0 and v2.1.0.

**Comment by jdalton** [comment]
That means lodash isn't being loaded properly.

**Comment by feross** [comment]
@jdalton This was a fresh npm install, and I can confirm that lodash is in the `node_modules` folder.

**Comment by feross** [comment]
This looks like it's caused by using `req('lodash')` which means browserify can't statically detect the `require` statement.

What's the point of wrapping `require` to suppress `module missing` errors when `lodash` is a dependency of `benchmark`? This just breaks browserify.

**Comment by jdalton** [comment]
Benchmark.js works in the browser without browserifying.

**Comment by jdalton** [comment]
Packages like `microtime` are optional which is why `req` surpasses the `module missing` errors.

**Comment by feross** [comment]
Fair enough, but `lodash` is not optional. Why use `req` for `lodash`?

**Comment by feross** [comment]
Also, why break browserify? Lots of code depended on require('benchmark') just working, for example: https://github.com/feross/buffer

**Comment by jdalton** [comment]
> Fair enough, but `lodash` is not optional. Why use `req` for `lodash`?

Packages like `microtime` are optional which is why `req` surpasses the `module missing` errors. Benchmark.js has traditionally run in more environments than just Node (like Rhino or Ringo).

> Also, why break browserify? Lots of code depended on require('benchmark') just working, for example:

It's not like I set out to break browserify geez. I believe you're the first person to bring up the browserify issue.
I'll look into making Benchmark.js more browserify friendly.

**Comment by feross** [comment]
> It's not like I set out to break browserify geez.

Sorry, it sounded like you were refusing to support browserify and the reasoning seemed silly given that `lodash` is required so I believe there's no reason to use `req`.

I know you didn't mean to break it. :smile: Cheers, and thanks for the good work!

**Comment by jdalton** [comment]
Let me know if https://github.com/bestiejs/benchmark.js/commit/7de5705328ec29afa14e8813498e9c6c2a97c0f4 helps.

**Comment by feross** [comment]
Now it returns `Error: Cannot find module 'microtime'` but I suppose that's easy enough to install manually as a workaround. Not ideal, though.

**Comment by jdalton** [comment]
Ok cool and how about https://github.com/bestiejs/benchmark.js/commit/c588a6bc349986cfb758486c0b04e8ee256a5ebb?

**Comment by feross** [comment]
Yep, works better.

Getting errors on [this line](https://github.com/bestiejs/benchmark.js/blob/c588a6bc349986cfb758486c0b04e8ee256a5ebb/benchmark.js#L681)

`(program):1 Uncaught ReferenceError: Benchmark is not defined`

But it doesn't seem to be preventing things from working. It's just spewing in the console at the moment.

**Comment by jdalton** [comment]
I'll keep digging.

**Comment by Ravenstine** [comment]
I too would like to see this fixed.  I'll report back if I find anything myself.

**Comment by sole** [comment]
Seeing this as well, and to add some more information than a simple '+1 me too' , it happened to me using Webpack too. I was getting fairly strange errors in both Firefox and Chrome so I tried using Browserify and eventually ended up on this page.

Screenshot of how bananas Chrome gets when trying to run the benchmark.js example compiled with Webpack:

<img width="1045" alt="screen shot 2016-05-06 at 11 01 34" src="https://cloud.githubusercontent.com/assets/5609/15070087/09ef68b0-137a-11e6-90d6-d2f11f17d752.png">

**Comment by Hypercubed** [comment]
I had to do the following for JSPM:

```
var process = require('process');
var benchmark = require('benchmark');
var _ = require('lodash');

if (typeof window !== 'undefined') {
  benchmark = benchmark.runInContext({_, process});
  window.Benchmark = benchmark;
}
```

**Comment by Hypercubed** [comment]
I'm having success running benchmarks in the browser using [Chūhai](https://github.com/Hypercubed/chuhai).  I tested with [testling](https://github.com/substack/testling), [browser-run](https://github.com/juliangruber/browser-run), and [zuul](https://github.com/defunctzombie/zuul).  The first two require [browserify](https://github.com/substack/node-browserify).

**Comment by rattrayalex** [comment]
Reporting here with basic webpack (no babel) usage: 

```js
// webpack.config.js
var path = require('path');

module.exports = {
  entry: './index.js',
  output: {
    filename: 'bundle.js',
  },
  devtool: 'eval-source-map',
  module: {
    noParse: [
      path.resolve(__dirname, './node_modules/benchmark/benchmark.js'),
    ]
  }
};
```
```js
// index.js
var _ = require('lodash');
var process = require('process');
var Benchmark = require('benchmark');
Benchmark = Benchmark.runInContext({ _: _, process: process });
var suite = new Benchmark.Suite();

suite
  .add('RegExp#test', function() {
      /o/.test('Hello World!');
    })
  .add('String#indexOf', function() {
      'Hello World!'.indexOf('o') > -1;
    })
  .add('String#match', function() {
      !!'Hello World!'.match(/o/);
    })
  // add listeners
  .on('cycle', function(event) {
      console.log(String(event.target));
    })
  .on('complete', function() {
      console.log('Fastest is ' + this.filter('fastest').map('name'));
    })
  // run async
  .run({ 'async': true });
```
```
// ouput: 
VM39740:1 Uncaught ReferenceError: Benchmark is not defined(anonymous function) @ VM39740:1runScript @ benchmark.js?482a:678createFunction @ benchmark.js?482a:514createFunction @ benchmark.js?482a:521createCompiled @ benchmark.js?482a:1698clock @ benchmark.js?482a:1592clock @ benchmark.js?482a:1802cycle @ benchmark.js?482a:1991run @ benchmark.js?482a:2098execute @ benchmark.js?482a:857(anonymous function) @ lodash.js?03cc:2414
VM39944:1 Uncaught ReferenceError: Benchmark is not defined(anonymous function) @ VM39944:1runScript @ benchmark.js?482a:678cycle @ benchmark.js?482a:2054(anonymous function) @ benchmark.js?482a:2045(anonymous function) @ lodash.js?03cc:2414

// ... repeats many times
RegExp#test x 7,428,626 ops/sec ±2.76% (50 runs sampled)
// ... error repeats many times again, along with following results printed out
```

**Comment by Hypercubed** [comment]
@rattrayalex Add the following line after the `runInContext` call.

```
window.Benchmark = Benchmark;
```

**Comment by rattrayalex** [comment]
Terrific, thanks @Hypercubed ! worked for me.

**Comment by nosovsh** [comment]
I'm still getting `Uncaught ReferenceError: define is not defined` same as @sole. I'm using webpack and npm.

trying with code that is analogical to what @Hypercubed and @rattrayalex suggested:

```
// index.js
var _ = require('benchmark/node_modules/lodash');
var process = require('process');
var Benchmark = require('benchmark');
Benchmark = Benchmark.runInContext({ _: _, process: process });
window.Benchmark = Benchmark;
var suite = new Benchmark.Suite();

suite
  .add('RegExp#test', function() {
    /o/.test('Hello World!');
  })
  .add('String#indexOf', function() {
    'Hello World!'.indexOf('o') > -1;
  })
  .add('String#match', function() {
    !!'Hello World!'.match(/o/);
  })
  // add listeners
  .on('cycle', function(event) {
    console.log(String(event.target));
  })
  .on('complete', function() {
    console.log('Fastest is ' + this.filter('fastest').map('name'));
  })
  // run async
  .run({ 'async': true });
```

Everything is working fine when including scripts in html page:
```
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.13.1/lodash.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/platform/1.3.1/platform.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/benchmark/2.1.0/benchmark.js"></script>
```

**Comment by julianvmodesto** [comment]
Using Webpack + Babel for my client-side. This thread was helpful and this is what I ended up with that works for me:

```
// package.json
  "dependencies": {
    "benchmark": "^2.1.3",
    "lodash": "^4.17.4",
  }

```

```
// webpack.config.js
  ...
  module: {
    noParse: [
      /benchmark/,
    ]
  },
  ...
```

```
import _ from 'lodash';
import process from 'process';

const benchmark = require('benchmark');
const Benchmark = benchmark.runInContext({ _, process });
window.Benchmark = Benchmark;
```

Seems like the noParse was important.

**Comment by timolawl** [comment]
I'm possibly having some trouble with the interaction between browserify and benchmark.js as well.

> TypeError: Cannot set property 'maxTime' of undefined

The problem appears when I use my production task:

```
gulp.task('build-js', () =>
  merge(...paths.entry.scripts.map(script =>
    browserify({
      entries: script,
      extensions: ['.jsx'],
      debug: true
    })
      .transform(babelify, { presets: ['env', 'react'] })
      .transform(envify)
      .transform({
        global: true
      }, uglifyify)
      .plugin(collapse)
      .bundle()
      .on('error', gutil.log.bind(gutil, 'Browserify error.'))
      .pipe(source(`./${script.split('/')[script.split('/').length - 1]}`))
      .pipe(buffer())
      .pipe(plumber())
      .pipe(rename(path => {
        path.extname = '.bundle.js';
      }))
      .pipe(uglify({ mangle: true }))
      .pipe(gulp.dest(`${ghPages}public/js`))
      .pipe(isGitHubPages ? gulpif('*sw.bundle.js', gulp.dest(ghPages)) : gutil.noop())
      .pipe(browserSync.reload({ stream: true }))
  ))
);
```

However, when I use my development task that has browserify in it, it works fine:

```
gulp.task('build-js-inc', () =>
  merge(...paths.entry.scripts.map(script => {
    const b = browserify(Object.assign({}, browserifyInc.args,
      {
        entries: script,
        extensions: ['.jsx'],
        debug: true
      }
    ));

    browserifyInc(b, { cacheFile: './browserify-cache.json' });

    return b.transform(babelify, { presets: ['env', 'react'] })
      .bundle()
        .on('error', handleErrors)
        .pipe(source(`./${script.split('/')[script.split('/').length - 1]}`))
        .pipe(buffer())
        .pipe(plumber())
        .pipe(rename(path => {
          path.extname = '.bundle.js';
        }))
        .pipe(gulp.dest('public/js'))
        .pipe(browserSync.reload({ stream: true }));
  }))
);
```

**Comment by drewlustro** [comment]
Thanks @julianvmodesto !

**Comment by mir3z** [comment]
This issue makes me think that 

> Benchmark.js is part of the BestieJS “Best in Class” module collection. This means we promote solid **browser/environment support**, ES5+ precedents, unit testing, & plenty of documentation.

is just an idle talk.

**Comment by heapwolf** [comment]
Result from piping `browserify` output to chrome headless.

```
> browserify --bare ./test/perf.js | tape-run

TypeError: Cannot read property 'parentNode' of undefined
    at runScript (http://localhost:52210/bundle.js:902:27)
    at createFunction (http://localhost:52210/bundle.js:755:9)
    at createFunction (http://localhost:52210/bundle.js:762:44)
    at createCompiled (http://localhost:52210/bundle.js:1952:23)
    at clock (http://localhost:52210/bundle.js:1846:58)
    at clock (http://localhost:52210/bundle.js:2056:20)
    at cycle (http://localhost:52210/bundle.js:2245:49)
    at Benchmark.run (http://localhost:52210/bundle.js:2352:13)
    at execute (http://localhost:52210/bundle.js:1098:74)
    at invoke (http://localhost:52210/bundle.js:1208:20)
```

This issue is caused by the assumption that there will be a `script` tag in the page (in some cases this is not true)... https://github.com/bestiejs/benchmark.js/blob/c588a6bc349986cfb758486c0b04e8ee256a5ebb/benchmark.js#L663

**Comment by jonkoops** [comment]
I am getting the same kind of issue when using Rollup, more info in #244
