### ISSUE TITLE
Unable to benchmark node streams (using transform-streams)

### ISSUE THREAD

**Issue by jfet97** [bestiejs/benchmark.js#215]
This is the test:

```
    const Benchmark = require('benchmark');
    const suite = new Benchmark.Suite;
    const fs = require('fs');
    const stream = require('stream');

    const uppercaser = new stream.Transform({
        transform: function (chunk, _, callback) {
            callback(null, chunk.toString().toUpperCase());
       }
    });

    suite.add('transform-streams', {
       defer: true,
       fn: function (deferred) {

            const readStream = fs.createReadStream('1.txt', {
               highWaterMark: 1024
            });
            const writeStream = fs.createWriteStream('write1.txt');

            readStream
               .pipe(uppercaser)
               .pipe(writeStream).on('finish', () => {
                   deferred.resolve();
                });
         }
    })
    .on('cycle', function (event) {
        console.log(String(event.target));
    }).on('complete', function () {
        console.log(this[0].stats)
    }).run()
```

This is the error:
```
    events.js:167
    throw er; // Unhandled 'error' event
    ^

    Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:243:12)
    at Transform.Writable.write (_stream_writable.js:291:5)
    at ReadStream.ondata (_stream_readable.js:666:20)
    at ReadStream.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at ReadStream.Readable.push (_stream_readable.js:219:10)
    at lazyFs.read (internal/fs/streams.js:181:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:460:17)

    Emitted 'error' event at:
    at Transform.onerror (_stream_readable.js:690:12)
    at Transform.emit (events.js:182:13)
    at writeAfterEnd (_stream_writable.js:245:10)
    at Transform.Writable.write (_stream_writable.js:291:5)
    [... lines matching original stack trace ...]
    at lazyFs.read (internal/fs/streams.js:181:12)
```

But my code does work standalone. I'm unable to do the test and I cannot understand why.

**Comment by jdalton** [comment]
Hi @jfet97!

I'm not too sure. You can remove Benchmark.js from the scenario though and put your `fn` body inside a for-loop that executes say a million times and see if you still get the issue.
